name: app_launcher
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_manager:
    git: https://github.com/nightmare-space/app_manager
  get: ^4.1.3
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  cupertino_icons: ^1.0.2

  flutter_spinkit: "^4.1.2"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

dependency_overrides:
  app_manager:
    path: /Users/nightmare/Desktop/nightmare-space/app_manager